### ISSUE TITLE
Json ใช้ Encoder กับ writer ง่ายกว่า

### ISSUE THREAD

**Issue by wingyplus** [armeo/go-mongo-rest#1]
จาก https://github.com/armeo/go-mongo-rest/blob/master/main.go#L14 และ https://github.com/armeo/go-mongo-rest/blob/master/main.go#L24 ใช้ json encoder ง่ายกว่า

``` go
json.NewEncoder(res).Encode(data)
```

**Comment by armeo** [comment]
จริงด้วย แถมเร็วกว่า Marshal ซะด้วย
