### ISSUE TITLE
ควรจะ Clone session ก่อนแล้วค่อยใช้งาน

### ISSUE THREAD

**Issue by iporsut** [armeo/go-mongo-rest#2]
จาก https://github.com/armeo/go-mongo-rest/blob/master/repos.go#L34
เห็นว่าทำการ Close session ไปเลยจะทำให้เรียกใช้อีกรอบไม่ได้เพราะใน document ของ mgo บอกเอาไว้ว่า

// Close terminates the session.  It's a runtime error to use a session
// after it has been closed.

ดังนั้นควรจะ clone ก่อนประมาณนี้

```
session := db.session.Clone()
defer session.Close()
collection := session.DB("notesdb").C("notes")
```

**Comment by armeo** [comment]
อ่า ... ขอบคุณครัช
